name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal 
    - name: Publish Website
      run: dotnet publish AnimalAdoption.Web.Portal --output ./publish --no-build --configuration Release  
    - name: Upload website Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Website-Artifacts
        path: ./publish/
        if-no-files-found: error
    - name: Nuget Package
      run: dotnet pack --configuration Release --no-restore --output ./Nuget AnimalAdoption.Common.Logic/AnimalAdoption.Common.Logic.csproj
    - name: Nuget Publish
      run: dotnet nuget push "./Nuget/*.nupkg"